"""
Audio engine v2 foundation package.
Exists to model the next DAW-style backend without replacing the live v1 runtime.
Connects playback planning to future real-time graph preparation through immutable data.
"""

from echozero.application.audio_engine_v2.graph import (
    MASTER_BUS_ID,
    GraphIdentity,
    HardwareOutputRoute,
    MixParameters,
    PreparedBus,
    PreparedGraph,
    PreparedTrack,
    RouteTarget,
    RouteTargetKind,
    SignalRoute,
    TrackRoute,
    compute_graph_identity,
    replace_track_mix,
    replace_track_route,
)
from echozero.application.audio_engine_v2.live_engine import V2LiveAudioEngine
from echozero.application.audio_engine_v2.offline_render import (
    OfflineRenderMemory,
    OfflineRenderResult,
    OfflineRenderState,
    OfflineSourceBank,
    TransitionPolicy,
    render_offline_block,
)
from echozero.application.audio_engine_v2.parity import (
    GraphEditClassification,
    GraphEditKind,
    GraphParitySummary,
    ParityPlanningError,
    PlannerParityReport,
    TrackRouteSummary,
    build_shadow_graph_from_playback_projection,
    build_shadow_graph_from_track_plan,
    classify_graph_edit,
    summarize_graph_parity,
)
from echozero.application.audio_engine_v2.rt_commands import (
    RtCommand,
    RtCommandBatch,
    RtCommandKind,
    RtCommandResult,
    RtRuntimeState,
    apply_rt_command_batch,
)
from echozero.application.audio_engine_v2.rt_graph import (
    RtBusNode,
    RtGraph,
    RtNodeKind,
    RtRouteTarget,
    RtTrackNode,
    prepare_rt_graph,
)
from echozero.application.audio_engine_v2.snapshot import (
    PlaybackSnapshotGeneration,
    create_snapshot_generation,
)
from echozero.application.audio_engine_v2.transport import (
    LoopRegion,
    TransportCommand,
    TransportCommandKind,
    TransportPlayState,
    TransportState,
    apply_transport_command,
)

__all__ = [
    "MASTER_BUS_ID",
    "GraphIdentity",
    "GraphEditClassification",
    "GraphEditKind",
    "GraphParitySummary",
    "HardwareOutputRoute",
    "LoopRegion",
    "MixParameters",
    "OfflineRenderMemory",
    "OfflineRenderResult",
    "OfflineRenderState",
    "OfflineSourceBank",
    "PlaybackSnapshotGeneration",
    "ParityPlanningError",
    "PreparedBus",
    "PreparedGraph",
    "PreparedTrack",
    "PlannerParityReport",
    "RouteTarget",
    "RouteTargetKind",
    "RtBusNode",
    "RtCommand",
    "RtCommandBatch",
    "RtCommandKind",
    "RtCommandResult",
    "RtGraph",
    "RtNodeKind",
    "RtRouteTarget",
    "RtRuntimeState",
    "RtTrackNode",
    "SignalRoute",
    "TrackRouteSummary",
    "TrackRoute",
    "TransitionPolicy",
    "TransportCommand",
    "TransportCommandKind",
    "TransportPlayState",
    "TransportState",
    "V2LiveAudioEngine",
    "apply_transport_command",
    "apply_rt_command_batch",
    "build_shadow_graph_from_playback_projection",
    "build_shadow_graph_from_track_plan",
    "classify_graph_edit",
    "compute_graph_identity",
    "create_snapshot_generation",
    "prepare_rt_graph",
    "render_offline_block",
    "replace_track_mix",
    "replace_track_route",
    "summarize_graph_parity",
]
