#!/usr/bin/env python3
"""
Generate documentation from codebase.

Scans the EchoZero codebase and generates up-to-date documentation
for the web interface.
"""
import os
import sys
import json
from pathlib import Path
from typing import Dict, List, Any
import importlib.util

# Add project root to path
project_root = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(project_root))

def get_block_types() -> List[Dict[str, Any]]:
    """Get all available block types from the registry."""
    try:
        from src.application.block_registry import BlockTypeRegistry
        
        registry = BlockTypeRegistry()
        registry.initialize_default_types()
        
        blocks = []
        for block_type in registry.list_all():
            blocks.append({
                "name": block_type.name,
                "type_id": block_type.type_id,
                "description": block_type.description,
                "inputs": {k: str(v) for k, v in block_type.inputs.items()},
                "outputs": {k: str(v) for k, v in block_type.outputs.items()},
                "execution_mode": block_type.execution_mode,
                "tags": block_type.tags
            })
        return blocks
    except Exception as e:
        print(f"Error getting block types: {e}")
        return []

def get_feature_modules() -> List[Dict[str, Any]]:
    """Get all feature modules."""
    features_dir = project_root / "src" / "features"
    features = []
    
    for feature_dir in features_dir.iterdir():
        if feature_dir.is_dir() and (feature_dir / "README.md").exists():
            readme_path = feature_dir / "README.md"
            with open(readme_path) as f:
                content = f.read()
            
            features.append({
                "name": feature_dir.name,
                "path": str(feature_dir.relative_to(project_root)),
                "readme": content
            })
    
    return features

def generate_docs_json() -> Dict[str, Any]:
    """Generate documentation data structure."""
    return {
        "blocks": get_block_types(),
        "features": get_feature_modules(),
        "version": "2.1",
        "last_updated": "2026-02-04"
    }

def generate_html_with_embedded_data(docs_data: Dict[str, Any]) -> str:
    """Generate HTML file with embedded JSON data."""
    html_template_path = project_root / "docs" / "index.html"
    
    # Read the template HTML
    with open(html_template_path, 'r') as f:
        html_content = f.read()
    
    # Create embedded data script
    embedded_js = f"""        // Embedded documentation data (generated by scripts/generate_docs.py)
        const embeddedDocsData = {json.dumps(docs_data, indent=8)};"""
    
    # Find and replace the marker comment
    marker = "// Documentation data will be embedded here by generate_docs.py"
    if marker in html_content:
        # Replace the marker and the following line with embedded data
        lines = html_content.split('\n')
        new_lines = []
        skip_next = False
        for i, line in enumerate(lines):
            if marker in line:
                new_lines.append(line)
                new_lines.append(embedded_js)
                skip_next = True
            elif skip_next and 'let docsData = null;' in line:
                new_lines.append(line)
                skip_next = False
            elif not skip_next:
                new_lines.append(line)
        
        html_content = '\n'.join(new_lines)
    else:
        # Fallback: insert before <script> tag
        html_content = html_content.replace(
            '<script>',
            f'<script>\n{embedded_js}\n',
            1
        )
    
    return html_content

def main():
    """Generate documentation files."""
    docs_dir = project_root / "docs"
    docs_dir.mkdir(exist_ok=True)
    
    # Generate JSON data
    docs_data = generate_docs_json()
    
    # Write JSON file (for API access)
    json_path = docs_dir / "docs.json"
    with open(json_path, 'w') as f:
        json.dump(docs_data, f, indent=2)
    
    # Generate HTML with embedded data (for file:// access)
    html_content = generate_html_with_embedded_data(docs_data)
    html_path = docs_dir / "index.html"
    with open(html_path, 'w') as f:
        f.write(html_content)
    
    print(f"Generated documentation:")
    print(f"  - JSON: {json_path}")
    print(f"  - HTML: {html_path} (with embedded data)")
    print(f"  - {len(docs_data['blocks'])} block types")
    print(f"  - {len(docs_data['features'])} feature modules")

if __name__ == "__main__":
    main()
